name: Docker Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ashwini-web:v1 .

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name test-container ashwini-web:v1
      - name: Test website response
        run: |
          sleep 5
          curl -f http://localhost:8080

      - name: Stop Docker container
        run: docker stop test-container
